import "../blocks/hero/hero.js";
import "../blocks/navi/navi.js";
import "../blocks/news/news.js";
import "../blocks/games/games.js";
import "../blocks/gm-slider/gm-slider.js";
import "../blocks/footer/footer.js";
import "../blocks/menu-1/menu-1.js";
import "../blocks/header/header.js";
import "../blocks/discipline/discipline.js";